# Generated by Django 4.1.1 on 2022-11-07 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_folder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesdb',
            name='shop_Code',
            field=models.CharField(blank=True, help_text='ショップコード', max_length=128, null=True),
        ),
    ]
