# Generated by Django 4.1.1 on 2022-11-07 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_folder', '0002_storesdb_shop_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='ichibaitemsdb',
            name='imageUrl',
            field=models.TextField(blank=True, help_text='画像Url', max_length=1024, null=True, verbose_name='画像Url'),
        ),
    ]
