# Generated by Django 4.1.1 on 2022-11-07 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_folder', '0003_ichibaitemsdb_imageurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='ichibaitemsdb',
            name='itemPrice',
            field=models.PositiveSmallIntegerField(blank=True, help_text='itemPrice', null=True, verbose_name='itemPrice'),
        ),
    ]
