# Generated by Django 4.1.1 on 2022-11-08 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_folder', '0004_ichibaitemsdb_itemprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='ichibaitemsdb',
            name='reviewAverage',
            field=models.FloatField(blank=True, help_text='reviewAverage', null=True, verbose_name='reviewAverage'),
        ),
        migrations.AddField(
            model_name='ichibaitemsdb',
            name='reviewCount',
            field=models.PositiveSmallIntegerField(blank=True, help_text='reviewCount', null=True, verbose_name='reviewCount'),
        ),
    ]
