# Generated by Django 4.1.1 on 2022-11-08 01:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app_folder', '0005_ichibaitemsdb_reviewaverage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IchibaItemsMonthlyDB',
            fields=[
                ('sys_datetime_created', models.DateTimeField(auto_now_add=True, help_text='作成日時')),
                ('sys_datetime_modified', models.DateTimeField(auto_now=True, help_text='更新日時')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='uuid', primary_key=True, serialize=False, unique=True)),
                ('monthly', models.DateTimeField(blank=True, help_text='マンスリー(YYYY/MM)', verbose_name='マンスリー(YYYY/MM)')),
                ('itemPrice', models.PositiveSmallIntegerField(blank=True, help_text='itemPrice', null=True, verbose_name='itemPrice')),
                ('reviewAverage', models.FloatField(blank=True, help_text='reviewAverage', null=True, verbose_name='reviewAverage')),
                ('reviewCount', models.PositiveSmallIntegerField(blank=True, help_text='reviewCount', null=True, verbose_name='reviewCount')),
                ('ichibaItems', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_ichibaItems_monthly_ichibaItems', to='app_folder.ichibaitemsdb', verbose_name='楽天市場商品ID')),
            ],
            options={
                'verbose_name_plural': 'tbl_ichibaItems_monthly',
                'db_table': 'tbl_ichibaItems_monthly',
            },
        ),
        migrations.CreateModel(
            name='IchibaItemsDailyDB',
            fields=[
                ('sys_datetime_created', models.DateTimeField(auto_now_add=True, help_text='作成日時')),
                ('sys_datetime_modified', models.DateTimeField(auto_now=True, help_text='更新日時')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='uuid', primary_key=True, serialize=False, unique=True)),
                ('daily', models.DateTimeField(blank=True, help_text='デイリー(YYYY/MM/DD)', verbose_name='デイリー(YYYY/MM/DD)')),
                ('itemPrice', models.PositiveSmallIntegerField(blank=True, help_text='itemPrice', null=True, verbose_name='itemPrice')),
                ('reviewAverage', models.FloatField(blank=True, help_text='reviewAverage', null=True, verbose_name='reviewAverage')),
                ('reviewCount', models.PositiveSmallIntegerField(blank=True, help_text='reviewCount', null=True, verbose_name='reviewCount')),
                ('ichibaItems', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_ichibaItems_daily_ichibaItems', to='app_folder.ichibaitemsdb', verbose_name='楽天市場商品ID')),
            ],
            options={
                'verbose_name_plural': 'tbl_ichibaItems_daily',
                'db_table': 'tbl_ichibaItems_daily',
            },
        ),
    ]
