# Generated by Django 4.1.1 on 2022-11-08 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_folder', '0006_ichibaitemsmonthlydb_ichibaitemsdailydb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemsdb',
            name='itemName',
            field=models.CharField(blank=True, help_text='商品名', max_length=256, null=True, verbose_name='商品名'),
        ),
        migrations.AlterField(
            model_name='itemsdb',
            name='itemUrl',
            field=models.CharField(blank=True, help_text='商品管理番号', max_length=256, null=True, verbose_name='商品管理番号'),
        ),
        migrations.AlterField(
            model_name='itemsdb',
            name='whiteBgImageUrl',
            field=models.CharField(blank=True, help_text='白背景画像URL', max_length=256, null=True, verbose_name='白背景画像URL'),
        ),
    ]
