# Generated by Django 4.1.1 on 2022-11-08 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_folder', '0007_alter_itemsdb_itemname_alter_itemsdb_itemurl_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ichibaitemsdailydb',
            name='summaryCount',
            field=models.PositiveSmallIntegerField(blank=True, help_text='summaryCount', null=True, verbose_name='summaryCount'),
        ),
        migrations.AddField(
            model_name='ichibaitemsmonthlydb',
            name='summaryCount',
            field=models.PositiveSmallIntegerField(blank=True, help_text='summaryCount', null=True, verbose_name='summaryCount'),
        ),
    ]
