# Generated by Django 4.1.1 on 2022-11-09 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_folder', '0008_ichibaitemsdailydb_summarycount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ichibaitemsdb',
            name='genreId',
            field=models.CharField(blank=True, help_text='genreId', max_length=8, null=True, verbose_name='genreId'),
        ),
    ]
