# Generated by Django 4.1.1 on 2022-11-09 08:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app_folder', '0009_ichibaitemsdb_genreid'),
    ]

    operations = [
        migrations.CreateModel(
            name='IchibaGenresDB',
            fields=[
                ('sys_datetime_created', models.DateTimeField(auto_now_add=True, help_text='作成日時')),
                ('sys_datetime_modified', models.DateTimeField(auto_now=True, help_text='更新日時')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='uuid', primary_key=True, serialize=False, unique=True)),
                ('genreId', models.CharField(blank=True, help_text='genreId', max_length=8, null=True, verbose_name='genreId')),
                ('genreName', models.CharField(blank=True, help_text='genreName', max_length=128, null=True, verbose_name='genreName')),
                ('genreLevel', models.PositiveSmallIntegerField(blank=True, help_text='genreLevel', null=True, verbose_name='genreLevel')),
                ('parentGenreId', models.CharField(blank=True, help_text='parentGenreId', max_length=8, null=True, verbose_name='parentGenreId')),
                ('malls', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_tmp_ichibaGenres_malls', to='app_folder.storesdb', verbose_name='モールID')),
            ],
            options={
                'verbose_name_plural': 'tmp_ichibaGenres',
                'db_table': 'tmp_ichibaGenres',
            },
        ),
    ]
