# Generated by Django 4.1.1 on 2022-11-10 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_folder', '0010_ichibagenresdb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ichibagenresdb',
            name='malls',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_tmp_ichibaGenres_malls', to='app_folder.mallsdb', verbose_name='モールID'),
        ),
    ]
