# Generated by Django 4.1.1 on 2022-11-11 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_folder', '0011_alter_ichibagenresdb_malls'),
    ]

    operations = [
        migrations.AddField(
            model_name='ichibaitemsdb',
            name='ichibaGenres',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_ichibaItems_ichibaGenres', to='app_folder.ichibagenresdb', verbose_name='楽天市場ジャンルID'),
        ),
    ]
