# Generated by Django 4.1.1 on 2022-11-12 13:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app_folder', '0012_ichibaitemsdb_ichibagenres'),
    ]

    operations = [
        migrations.CreateModel(
            name='IchibaRankingsDB',
            fields=[
                ('sys_datetime_created', models.DateTimeField(auto_now_add=True, help_text='作成日時')),
                ('sys_datetime_modified', models.DateTimeField(auto_now=True, help_text='更新日時')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='uuid', primary_key=True, serialize=False, unique=True)),
                ('genreId', models.CharField(blank=True, help_text='genreId', max_length=8, null=True, verbose_name='genreId')),
                ('itemCode', models.CharField(blank=True, help_text='itemCode', max_length=64, null=True, verbose_name='itemCode')),
                ('rank', models.PositiveSmallIntegerField(blank=True, help_text='rank', null=True, verbose_name='rank')),
                ('shopCode', models.CharField(blank=True, help_text='shopCode', max_length=32, null=True, verbose_name='shopCode')),
                ('ichibaGenres', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_ichibaRankings_ichibaGenres', to='app_folder.ichibagenresdb', verbose_name='楽天市場ジャンルID')),
                ('ichibaItems', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_ichibaRankings_ichibaItems', to='app_folder.ichibaitemsdb', verbose_name='楽天市場商品ID')),
                ('stores', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_ichibaRankings_stores', to='app_folder.storesdb', verbose_name='ストアID')),
            ],
            options={
                'verbose_name_plural': 'tbl_ichibaRankings',
                'db_table': 'tbl_ichibaRankings',
            },
        ),
    ]
