# Generated by Django 4.1.1 on 2022-11-12 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_folder', '0013_ichibarankingsdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='ichibarankingsdb',
            name='lastBuildDate',
            field=models.DateTimeField(help_text='lastBuildDate', null=True),
        ),
        migrations.AddField(
            model_name='ichibarankingsdb',
            name='title',
            field=models.CharField(blank=True, help_text='title', max_length=256, null=True, verbose_name='title'),
        ),
    ]
