# Generated by Django 4.1.1 on 2022-11-15 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_folder', '0014_ichibarankingsdb_lastbuilddate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ichibagenresdb',
            name='ichibaGenres_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_tmp_ichibaGenres_ichibaGenres_parent', to='app_folder.ichibagenresdb', verbose_name='ichibaGenres_parent'),
        ),
    ]
