# Generated by Django 4.1.1 on 2022-11-16 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_folder', '0016_alter_ichibagenresdb_ichibagenres_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ichibagenresdb',
            name='ichibaGenres_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='related_tmp_ichibaGenres_ichibaGenres_parent', to='app_folder.ichibagenresdb', verbose_name='ichibaGenres_parent'),
        ),
    ]
