# Generated by Django 4.1.1 on 2022-11-19 01:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app_folder', '0017_alter_ichibagenresdb_ichibagenres_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='IchibaItemGenresDB',
            fields=[
                ('sys_datetime_created', models.DateTimeField(auto_now_add=True, help_text='作成日時')),
                ('sys_datetime_modified', models.DateTimeField(auto_now=True, help_text='更新日時')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='uuid', primary_key=True, serialize=False, unique=True)),
                ('ichibaGenres', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_ichibaItemGenres_ichibaGenres', to='app_folder.ichibagenresdb', verbose_name='楽天市場ジャンルID')),
                ('ichibaItems', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_ichibaItemGenres_ichibaItems', to='app_folder.ichibaitemsdb', verbose_name='楽天市場商品ID')),
                ('stores', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_ichibaItemGenres_stores', to='app_folder.storesdb', verbose_name='ストアID')),
            ],
            options={
                'verbose_name_plural': 'tmp_ichibaItemGenres',
                'db_table': 'tmp_ichibaItemGenres',
            },
        ),
    ]
