# Generated by Django 4.1.1 on 2022-11-21 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_folder', '0018_ichibaitemgenresdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='ichibarankingsdb',
            name='ichibaItemGenres',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_ichibaRankings_ichibaItemGenres', to='app_folder.ichibaitemgenresdb', verbose_name='楽天市場商品ジャンルID'),
        ),
    ]
