# Generated by Django 4.1.1 on 2022-11-23 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_folder', '0019_ichibarankingsdb_ichibaitemgenres'),
    ]

    operations = [
        migrations.AddField(
            model_name='ichibarankingsdb',
            name='ichibaRankingGenres',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_ichibaRankings_ichibaRankingGenres', to='app_folder.ichibagenresdb', verbose_name='楽天市場ランキングジャンルID'),
        ),
    ]
