# Generated by Django 4.1.1 on 2022-11-28 06:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app_folder', '0020_ichibarankingsdb_ichibarankinggenres'),
    ]

    operations = [
        migrations.CreateModel(
            name='YearsDB',
            fields=[
                ('sys_datetime_created', models.DateTimeField(auto_now_add=True, help_text='作成日時')),
                ('sys_datetime_modified', models.DateTimeField(auto_now=True, help_text='更新日時')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='uuid', primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, help_text='管理名', max_length=128, null=True)),
                ('datetime_start', models.DateTimeField(help_text='開始日時')),
                ('datetime_end', models.DateTimeField(help_text='終了日時')),
            ],
            options={
                'verbose_name_plural': 'mst_years',
                'db_table': 'mst_years',
            },
        ),
        migrations.CreateModel(
            name='MonthsDB',
            fields=[
                ('sys_datetime_created', models.DateTimeField(auto_now_add=True, help_text='作成日時')),
                ('sys_datetime_modified', models.DateTimeField(auto_now=True, help_text='更新日時')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='uuid', primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, help_text='管理名', max_length=128, null=True)),
                ('datetime_start', models.DateTimeField(help_text='開始日時')),
                ('datetime_end', models.DateTimeField(help_text='終了日時')),
                ('years', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_months_years', to='app_folder.yearsdb', verbose_name='yearsID')),
            ],
            options={
                'verbose_name_plural': 'mst_months',
                'db_table': 'mst_months',
            },
        ),
        migrations.CreateModel(
            name='DaysDB',
            fields=[
                ('sys_datetime_created', models.DateTimeField(auto_now_add=True, help_text='作成日時')),
                ('sys_datetime_modified', models.DateTimeField(auto_now=True, help_text='更新日時')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='uuid', primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, help_text='管理名', max_length=128, null=True)),
                ('datetime_start', models.DateTimeField(help_text='開始日時')),
                ('datetime_end', models.DateTimeField(help_text='終了日時')),
                ('months', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_days_months', to='app_folder.monthsdb', verbose_name='monthsID')),
            ],
            options={
                'verbose_name_plural': 'mst_days',
                'db_table': 'mst_days',
            },
        ),
    ]
